version: '3.1'

networks:
  monitor-net:
    driver: bridge

services:

  elasticsearch:
    image: elasticsearch:8.13.3
    container_name: elasticsearch    
    networks:
      - monitor-net
    ports:
      - 9100:9100
  
# docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic

# Password for the [elastic] user successfully reset.
# New value: ukb5NW4ABLZ7qpF=rObY

# docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana


  kibana:
    image: kibana:8.13.3
    container_name: kibana  
    networks:
      - monitor-net      
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch    
 

  logstash:
    image: logstash:8.13.3
    container_name: logstash  
    networks:
      - monitor-net      
    ports:
      - 5044:5044/udp
    depends_on:
      - elasticsearch      
    # volumes:
    #   logstash.yml:/usr/share/logstash/config/logstash.yml
    #   logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    # command: logstash -f /usr/share/logstash/pipeline/logstash.conf         



    
