version: '3'
services:

  kibana:
    image: kibana:8.13.4
    container_name: kibana  
    networks:
      - elastic  
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch 

  elasticsearch:
    image: rapidfort/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic

             
  logstash:
    image: taothong/logstash:1.0
    container_name: logstash     
    ports:
      - "5044:5044"
      - "5044:5044/udp"
    cap_add:
      - SYS_PTRACE
    volumes:
      # - ./logstash/pipelines.yml:/etc/logstash/pipelines.yml
      # - ./logstash/logstash.yml:/etc/logstash/logstash.yml

      # - ./logstash/30-elasticsearch-output.conf:/etc/logstash/conf.d/30-elasticsearch-output.conf
      # - ./logstash/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf

      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
      # - ./logstash-plain.log:/var/log/logstash/logstash-plain.log 

    # depends_on:
    #   - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge      