# Promtail Server Config
server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Positions
positions:
  filename: /tmp/positions.yaml

# Loki Server URL
clients:
  - url: http://loki:3100/loki/api/v1/push

# ---------------------local machine logs--------------------------
scrape_configs:
  - job_name: local
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
          # __path__: /var/log/grafana/*log
          # __path__: /var/log/lighttpd/*log
          # __path__: /var/log/letsencrypt/*log
          # __path__: /var/log/apt/*log


#---------------------- docker logse ---------------------------------
# scrape_configs:
#   - job_name: docker
#     pipeline_stages:
#       - docker: {}
#     static_configs:
#       - labels:
#           job: docker
#           __path__: /var/lib/docker/containers/*/*-json.log

#---------------------- syslog ---------------------------------
# scrape_configs:
#   - job_name: syslog
#     syslog:
#       listen_address: 0.0.0.0:1514
#       listen_protocol: tcp
#       idle_timeout: 60s
#       label_structured_data: yes
#       labels:
#         job: "syslog"
#     relabel_configs:
#       - source_labels: ['__syslog_message_hostname']
#         target_label: 'host'