version: '3'
services:

  kibana:
    image: kibana:8.13.4
    container_name: kibana  
    networks:
      - elastic  
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch 

  elasticsearch:
    image: rapidfort/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastic


  
networks:
  elastic:
    driver: bridge      