version: '3'
services:
 
  kibana:
    image: kibana:8.13.3
    container_name: kibana
    # restart: always
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch      
    networks:
      - elastic-net  

  elasticsearch:
    image: rapidfort/elasticsearch:8.13.3
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elastic-net            
  
  filebeat:
    image: elastic/filebeat:8.13.4
    container_name: filebeat
    # restart: always
    # volumes:
      # - ./filebeat2.docker.yml/:/usr/share/filebeat/filebeat.yml
      # - ./logs:/usr/share/filebeat/logs/

    # command: -e --strict.perms=false
    depends_on:
      - elasticsearch
    networks:
      - elastic-net      
    ports:
      - "9004:9004"      


volumes:
  elasticsearch_data:
    driver: local
  metricbeat-data:
    driver: local    

networks:
  elastic-net:
     driver: bridge        

# docker exec -it filebeat bash   
